on:
  push:
    branches:
      - main

jobs:
  run_pull:
    name: run_pull
    runs-on: ubuntu-latest

    steps:
    - name: Install SSH key
      run: |
        install -m 600 -D /dev/null ~/.ssh/bofc
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/bofc
        ssh-keyscan -H "${{ secrets.SSH_HOST }}" > ~/.ssh/known_hosts
    - name: Connect and pull
      run: ${{ secrets.SSH_USER }}@{{ secrets.SSH_HOST }} "cd ${{ secrets.WORK_DIR }} && git checkout ${{ secrets.MAIN_BRANCH }} && git pull"
    - name: Cleanup
      run: rm -rf ~/.ssh
